### ISSUE TITLE
Create Requirements for the Project Page

### ISSUE THREAD

**Issue by Jonathynlee** [Jonathynlee/CDSBusinessHealthApp#9]
Write a list of requirements for the project page, post to github for group approval.
-Please include API calls you will use for basecamp and what we will need to implement. 
-Also list how a user will connect their account to the API

**Comment by AysenUnlu** [comment]
https://docs.google.com/document/d/1ToDmMaAvi-8y1KKRic05MbYsfOvt1WzOwRfFSbnQNL0/edit?usp=sharing
